### ISSUE TITLE
Does not work properly between certain latitudes

### ISSUE THREAD

**Issue by ezonius** [hetima/DSP_SplitterOverBelt#1]
Between 41° 50' N to 46° 50' N and between 41° 50' S to 46° 50' S , the results become this: 
![image](https://user-images.githubusercontent.com/61872098/122653597-e5021680-d145-11eb-9f76-d86fc024b7ef.png)

**Comment by hetima** [comment]
Fixed in version 1.0.1. Thanks!

**Comment by JamieRCHI** [comment]
Broken again with todays game update. I removed all other mods and tested with just this one. 
Also tested in two different locations on my planet so appears to be broken everywhere.
My results are as shown in the above picture.

**Comment by hetima** [comment]
It was probably fixed in ~~1.0.2~~ 1.0.3. Thanks.

**Comment by JamieRCHI** [comment]
Works great again. Thank you very much.
