### ISSUE TITLE
Error Occuring building splitter on 3rd planet

### ISSUE THREAD

**Issue by TW3ET** [hetima/DSP_SplitterOverBelt#11]
Used the mode fine on first 2 planets, now when building on my 3rd planet I'm getting this error message. It prevents placing any splitter, overlapping or not.

System.MissingMethodException: int NearColliderLogic.GetBuildingsInAreaNonAlloc(UnityEngine.Vector3,single,int[],bool)
  at SplitterOverBelt.SplitterOverBelt+Patch.BuildTool_Click_CreatePrebuilds_Prefix (BuildTool_Click __instance) [0x00048] in0 
  at BuildTool_Click.CreatePrebuilds () [0x00005] in0 
  at BuildTool_Click._OnTick (System.Int64 time) [0x0006a] in0 
  at BuildTool._GameTick (System.Int64 time) [0x000cf] in0 
== Mod patches on the stack ==
CreatePrebuilds(Prefix): static void SplitterOverBelt.SplitterOverBelt+Patch::BuildTool_Click_CreatePrebuilds_Prefix(BuildTool_Click __instance)

**Comment by NicolasIRAGNE** [comment]
Just ran into the same error since today, I think the game had a small update earlier, perhaps it is connected

**Comment by TW3ET** [comment]
That would make more sense, I didn't notice an update so good catch.

**Comment by Phyrexien** [comment]
Yeh I had been using it without issue today, then when I restarted the game and it updated, immedietely recieved this error.

**Comment by hetima** [comment]
Might be fixed in 1.1.7.
