### ISSUE TITLE
Error when I switch between versions with tab

### ISSUE THREAD

**Issue by IgorGir** [hetima/DSP_SplitterOverBelt#5]
![erreur](https://user-images.githubusercontent.com/92496107/137240011-cea38692-b4f1-4121-81a6-ae7068bf4de9.png)

**Comment by hetima** [comment]
The error is caused by another mod "CopyInserters".
That's already an unnecessary mod, so uninstall it.

**Comment by IgorGir** [comment]
Uninstall which one ?
Splitter over belt ?

**Comment by hetima** [comment]
CopyInserters

**Comment by IgorGir** [comment]
OK thank you :)
