### ISSUE TITLE
Not compatible with PlanetwideMining mod

### ISSUE THREAD

**Issue by JamieRCHI** [hetima/DSP_SplitterOverBelt#7]
The game gives an error telling me I cannot place the splitter.

I also noted that the DLL is not showing the correct version in all of your mods. Checked the DLL's in another mod from another author, and all the DLLs are showing the correct version for their mods. 

I am using the Galactic scale mod, with a planet size of 400. Trying to place on the equator. Not sure if this makes a difference or not.

Thanks for your time in looking at this.

**Comment by hetima** [comment]
First, 1.0.6 will show up as 1.0.5 because I forgot to increment number. If the file modification date of the DLL is 2022, it is 1.0.6. (I don't use r2modman, so I don't know about that)

1.0.6 requires 0.9.24.11209 game version. 11209 is important, it is latest patch.

I tried GalacticScale with size of 400 and could not find a problem.

Do you have any more information or screenshots?

**Comment by JamieRCHI** [comment]
According to E:\SteamLibrary\steamapps\common\Dyson Sphere Program\Configs\versions file, I am at the latest game version which matches what you have. (I find it strange that DSPGAME.exe has a different version from the game. This is not standard from my experience working at Microsoft. Or is it something to do with the game engine?)

I'll create a new game with only this mod and check again. Maybe I can find a mod conflict. I also posted my modlist if that will help.

Also note that the version of the mod correctly shows in R2modman and in the manifest.json file that comes with the mod. The file SplitterOverBelt.dll shows as version 
1.0.0.0 in the File Explorer. So basically, not a big deal.

[modlist.txt](https://github.com/hetima/DSP_SplitterOverBelt/files/7931109/modlist.txt)

**Comment by JamieRCHI** [comment]
Found that the PlanetwideMining mod is preventing this one to work.
Edit: 
FYI. Found that with PlanetwideMining enabled and BuildingMoreDense
enabled, I can get DSP_SplitterOverBelt to partly work. 
The basic splitter type works but the other two alternate splitter types don't work.
